apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato
        image: surajkk93/zomato:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec:
  selector:
    app: zomato
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
